##
## EPITECH PROJECT, 2022
## libice
## File description:
## Makefile
##

all:
	make -C ./ice/
	make -C ./list/
	make -C ./engine/

clean:
	make fclean -C ./ice/
	make fclean -C ./list/
	make fclean -C ./engine/

fclean:		clean

re:			fclean all

.PHONY:		all clean fclean re

.SILENT:
